### ISSUE TITLE
Infografia_Relidad-Aumentada-Virtual-y-mixta_IrvingFernando

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-IrvingFernand0#1]

**Comment by IrvingFernand0** [comment]
[Realidad_Aumentada-Virtual-y-Mixta--IrvingFernandoReyesPacheco.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-IrvingFernand0/files/14230935/Realidad_Aumentada-Virtual-y-Mixta--IrvingFernandoReyesPacheco.pdf)

**Comment by magaly1311** [comment]
Excelente 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
